### ISSUE TITLE
broken link in main readme file

### ISSUE THREAD

**Issue by uludag** [sbmlteam/moccasin#19]
Link given as part of the following sentence is broken:

> You can view the SBML output for this example [in a separate file](docs/project/examples/example.xml)

**Comment by mhucka** [comment]
Thanks for reporting this. I have no idea what happened to that file – can't find it anywhere. I'll regenerate it.

**Comment by mhucka** [comment]
Fixed by commit 3b9a9f9

**Comment by uludag** [comment]
Thanks
