### ISSUE TITLE
Improve installation process

### ISSUE THREAD

**Issue by mhucka** [sbmlteam/moccasin#26]
At least one person (Jim Sluka) reported having extreme difficulties in installing the system, to the point where they gave up.

**Comment by mhucka** [comment]
tried building a standalone using pyinstaller and also cxfree, but couldn't get it to work. Try creating clean environment from which to use pyjnstaller or cxfree -- maybe it's failing because I have such a hacked python environment

**Comment by mhucka** [comment]
Things to try:

- [ ] investigate option: anaconda
- [ ] investigate option: standalone executable

**Comment by sd947** [comment]
Hi! I trying to install moccasin on Mac but keep getting this error: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; 'int' object is not iterable

I am not a python user and don't know how to fix this. I have installed libSBML through anaconda though and can import it if I open python but I don't know about any of the other dependencies.

**Comment by sd947** [comment]
Thank you! Fingers crossed we can figure it out somehow because I would really like to use this toolkit it looks great!

**Comment by mhucka** [comment]
Minor update: in order to try to catch all dependencies and figure out all issues that might arise during installation, I've been starting from scratch using new VMs, and it's been surprisingly hard getting all the Python bits installed. Still working on it ...

**Comment by mhucka** [comment]
By the way, @sd947 what is the operating system and Python environment you're using?

**Comment by sd947** [comment]
Thanks for the update! I am using macOS Sierra 10.12.6 and then python
3.6.5 in IDLE

**Comment by sd947** [comment]
Great thanks. Let me know when its ready for use and I will give it a go!

Steph

**Comment by mhucka** [comment]
@sd947 Hi – in the branch [wip-release-1.2](https://github.com/sbmlteam/moccasin/tree/wip-release-1.2), the installation process has been hopefully much improved, and there are more detailed instructions for different operating systems. I tested it in macOS High Sierra with Python 3.5 and a command-line environment, but hopefully it will work in macOS 10.12 too and in environments like IDLE.

If you're interested and able to get it from the branch, it's available for use now. Otherwise, I need to do more testing for a bug fix involving another issue (#51) but I hope to do a full release sometime this week.

**Comment by mhucka** [comment]
Closing this issue ahead of impending release of version 1.2.

**Comment by sd947** [comment]
Thanks Mike, this has been working well for me!
