### ISSUE TITLE
Have we solved libsbml install issue for tox?

### ISSUE THREAD

**Issue by mhucka** [sbmlteam/moccasin#28]
Previous issue noted by someone: to properly install Moccasin in the virtual environments, tox requires that all project dependencies in the requirements.txt file are installed by using pip, which python-libsbml doesn't allow. This means that the python-libsbml library is missing in all testing envs, which leads to converter tests failing and low coverage reports for the converter and converter test file (resulting in 54% cov). I am not sure how to fix this issue, but I've asked Frank for advice since I reported this on sourceforge thinking is was a python packaging error.

**Comment by mhucka** [comment]
I can no longer recall what this is about, and actually I don't think it's an issue, since we are running automated tests in Travis and they work (and we get > 75% coverage). I'm going to close this as not a bug anymore.

**Comment by matthiaskoenig** [comment]
Also using pyhon-libsbml with pip in ci without any issues in other
projects.
