### ISSUE TITLE
Usage in run-syntax-tests.py need to correct

### ISSUE THREAD

**Issue by georgethrax** [sbmlteam/moccasin#44]
Usage in run-syntax-tests.py need to correct

'''Usage: run-syntax-tests.py [-d] [-v]'''
would be corrected as
'''Usage: run-syntax-tests.py [-n] [-v]'''

**Comment by mhucka** [comment]
Fixed in commit e428723e56f4c979cf013df5a1852468284d00f9 and it will be in the next release. Thank you for the report!
